### ISSUE TITLE
Question: EToday of current day not written to database

### ISSUE THREAD

**Issue by mahadi** [SBFspot/SBFspot#444]
Question:
When i use `/usr/local/bin/sbfspot.3/SBFspot -v3 -ad1 -am0 -ae0 -finq -cfg/usr/local/bin/sbfspot.3/SBFspot.cfg` the total yield of the current day is not inserted into the database. 

I would like to see the current state of the day in my personal visualization which queries the SBFSpot database.

I guess it is related to the implementation? Does SBFspot handle updating of existing data or does it only insert into the database?
Or what is the reason that it is not inserted in the database?

**Comment by sbf-** [comment]
See #290 
I am working on a fix

**Comment by sbf-** [comment]
Fixed in V3.8.0

**Comment by mahadi** [comment]
@sbf-: I think this issue is not yet solved, just updated to V3.8.2. Existing values in the database are not updated, so still the current value (EToday) is not present... Is it true that updating is not supported?

**Comment by sbf-** [comment]
What do you mean with "existing values"?
In which table you're looking?

**Comment by mahadi** [comment]
I am querying the MonthData table and as set in the cron job, it gets updated only once a day. So this means the energey produced at the current can not be read from this table.

![grafik](https://user-images.githubusercontent.com/124618/124459149-232a4780-dd8e-11eb-8fe9-45a5d937c26f.png)

**Comment by sbf-** [comment]
Monthdata doesn't have EToday until the day is complete. So, July 5th is inserted the next day.
What you need is the Inverters table. There you have the updated EToday for each inverter.
